#!/usr/bin/env node
/**
 * Regenerates the MY MONDAY TASKS snapshot inside each team focus page from
 * the live LACE boards. Run nightly by .github/workflows/refresh-tasks.yml.
 *
 *   MONDAY_API_TOKEN=... node scripts/refresh-tasks.mjs
 *
 * Flags:
 *   --check          print what would change, write nothing, exit 1 if stale
 *   --html <file>    refresh one page (default: all configured pages)
 *   --user-id <id>   Monday user id (with --html; overrides env for that run)
 *   --input <file>   read saved board records instead of calling the API
 *   --output <file>  save the fetched board records (makes an --input fixture)
 *
 * Board config and transforms live in functions/_lib/monday-tasks.js (shared
 * with the live /api/tasks/:slug endpoint).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BOARDS,
  fetchAllBoards,
  tasksForUser,
  todayET,
  userIdForSlug,
} from "../functions/_lib/monday-tasks.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

const FOCUS_PAGES = [
  { slug: "marlie", name: "Marlie", userId: userIdForSlug("marlie") },
  { slug: "olivia", name: "Olivia", userId: userIdForSlug("olivia") },
  { slug: "carolina", name: "Carolina", userId: userIdForSlug("carolina") },
  { slug: "ashley", name: "Ashley", userId: userIdForSlug("ashley") },
];

/* ---- args ------------------------------------------------------------- */
const argv = process.argv.slice(2);
const flag = (name) => argv.includes(name);
const value = (name) => { const i = argv.indexOf(name); return i === -1 ? null : argv[i + 1]; };
const CHECK = flag("--check");
const INPUT = value("--input");
const OUTPUT = value("--output");
const HTML_ARG = value("--html");
const USER_ID_ARG = value("--user-id") ? Number(value("--user-id")) : null;

/* JSON.stringify leaves "</script" intact, which would close the inline
   <script> early if an item name ever contained it. */
const js = (str) => JSON.stringify(str).replace(/<\//g, "<\\/");

function render(tasks, eol) {
  const lines = [];
  for (const board of BOARDS) {
    const mine = tasks.filter((t) => t.b === board.key);
    if (!mine.length) continue;
    lines.push(`      // ---- ${board.heading} ----`);
    for (const t of mine) {
      lines.push(
        `      { b:${js(t.b)}, cat:${js(t.cat)}, n:${js(t.n)}, s:${js(t.s)}, ` +
          `due:${t.due ? js(t.due) : "null"}, id:${js(t.id)}${t.shared ? ", shared:true" : ""} },`
      );
    }
  }
  return lines.join(eol);
}

/* ---- page rewrite ----------------------------------------------------- */
const START = "// >>> TASKS-START — generated by scripts/refresh-tasks.mjs, do not hand-edit";
const END = "// <<< TASKS-END";

function readBlock(html, htmlPath) {
  const from = html.indexOf(START);
  const to = html.indexOf(END);
  if (from === -1 || to === -1 || to < from) {
    throw new Error(`${htmlPath} is missing the ${START.slice(0, 22)} / ${END} markers`);
  }
  const bodyStart = html.indexOf("\n", from) + 1;
  const bodyEnd = html.lastIndexOf("\n", to) + 1;
  return { bodyStart, bodyEnd, body: html.slice(bodyStart, bodyEnd) };
}

function parseBlock(body) {
  const out = new Map();
  const line = /\{\s*b:"([^"]+)",\s*cat:"((?:[^"\\]|\\.)*)",\s*n:"((?:[^"\\]|\\.)*)",\s*s:"(\w+)",\s*due:(null|"[\d-]+"),\s*id:"(\d+)"(,\s*shared:true)?\s*\}/g;
  for (const m of body.matchAll(line)) {
    out.set(m[6], {
      b: m[1],
      cat: JSON.parse(`"${m[2]}"`),
      n: JSON.parse(`"${m[3]}"`),
      s: m[4],
      due: m[5] === "null" ? null : JSON.parse(m[5]),
      id: m[6],
      shared: Boolean(m[7]),
    });
  }
  return out;
}

function summarize(before, after) {
  const added = [], removed = [], changed = [];
  for (const t of after) {
    const old = before.get(t.id);
    if (!old) { added.push(t); continue; }
    const deltas = ["cat", "n", "s", "due", "shared", "b"]
      .filter((k) => (old[k] ?? null) !== (t[k] ?? null))
      .map((k) => `${k}: ${JSON.stringify(old[k] ?? null)} -> ${JSON.stringify(t[k] ?? null)}`);
    if (deltas.length) changed.push({ t, deltas });
  }
  const live = new Set(after.map((t) => t.id));
  for (const [id, t] of before) if (!live.has(id)) removed.push(t);
  return { added, removed, changed };
}

function refreshPage({ slug, name, userId }, byBoard, date, unmapped) {
  const htmlPath = join(ROOT, slug, "index.html");
  let html = readFileSync(htmlPath, "utf8");

  const pageBoards = new Set(
    [...(html.match(/const BOARDS = \{[\s\S]*?\n {4}\};/)?.[0] || "").matchAll(/^\s{6}(\w+):\s*\{/gm)].map((m) => m[1])
  );

  const { tasks, unmapped: pageUnmapped } = tasksForUser(byBoard, userId);
  for (const u of pageUnmapped) unmapped.add(u);

  const orphan = [...new Set(tasks.map((t) => t.b))].filter((k) => !pageBoards.has(k));
  if (orphan.length) {
    throw new Error(
      `Board key(s) ${orphan.join(", ")} are not in ${slug}/index.html's BOARDS map.`
    );
  }

  const { bodyStart, bodyEnd, body } = readBlock(html, `${slug}/index.html`);
  const { added, removed, changed } = summarize(parseBlock(body), tasks);

  const eol = body.includes("\r\n") ? "\r\n" : "\n";
  const rendered = render(tasks, eol) + eol;
  const tasksChanged = rendered !== body;
  let next = html.slice(0, bodyStart) + rendered + html.slice(bodyEnd);
  next = next.replace(/const SNAPSHOT_DATE = "[\d-]{10}";/, `const SNAPSHOT_DATE = "${date}";`);

  console.log(`\n=== ${name} (${slug}/) — user ${userId} ===`);
  console.log(`${tasks.length} tasks across ${new Set(tasks.map((t) => t.b)).size} boards`);
  for (const t of added) console.log(`  + ${t.n} (${t.cat} · ${t.b})`);
  for (const t of removed) console.log(`  - ${t.n} (${t.cat} · ${t.b})`);
  for (const { t, deltas } of changed) console.log(`  ~ ${t.n} — ${deltas.join(", ")}`);
  if (!tasksChanged) console.log("  (no task changes)");

  const pageChanged = next !== html;
  if (CHECK) return { slug, tasksChanged, pageChanged, wrote: false };

  if (!pageChanged) {
    console.log(`  Page already current — nothing to write.`);
    return { slug, tasksChanged, pageChanged: false, wrote: false };
  }

  writeFileSync(htmlPath, next);
  console.log(`  Wrote ${slug}/index.html (SNAPSHOT_DATE ${date}).`);
  return { slug, tasksChanged, pageChanged: true, wrote: true };
}

/* ---- main ------------------------------------------------------------- */
const token = process.env.MONDAY_API_TOKEN;
if (!INPUT && !token) {
  console.error("MONDAY_API_TOKEN is not set (repo secret MONDAY_API_TOKEN feeds the nightly run).");
  process.exit(2);
}

let pages;
if (HTML_ARG) {
  const slug = HTML_ARG.replace(/\\/g, "/").replace(/^\.\//, "").replace(/\/index\.html$/, "");
  const match = FOCUS_PAGES.find((p) => p.slug === slug || `${p.slug}/index.html` === HTML_ARG);
  const userId = USER_ID_ARG || match?.userId;
  if (!userId) {
    console.error(`No Monday user id for ${HTML_ARG}. Pass --user-id or set MONDAY_USER_ID_${slug.toUpperCase()}.`);
    process.exit(2);
  }
  pages = [{ slug: match?.slug || slug, name: match?.name || slug, userId }];
} else {
  pages = FOCUS_PAGES.filter((p) => p.userId > 0);
  const skipped = FOCUS_PAGES.filter((p) => p.userId <= 0);
  for (const p of skipped) {
    console.log(`Skipping ${p.name} — set MONDAY_USER_ID_${p.slug.toUpperCase()} to enable nightly refresh.`);
  }
  if (!pages.length) {
    console.error("No focus pages configured with a Monday user id.");
    process.exit(2);
  }
}

const byBoard = INPUT
  ? JSON.parse(readFileSync(INPUT, "utf8"))
  : await fetchAllBoards(token);

if (OUTPUT) writeFileSync(OUTPUT, JSON.stringify(byBoard, null, 1) + "\n");

const date = todayET();
const unmapped = new Set();
const results = [];

for (const page of pages) {
  results.push(refreshPage(page, byBoard, date, unmapped));
}

if (unmapped.size) {
  console.log(`\nUnrecognized status label(s), treated as "Not started" — add them to STATUS_MAP:`);
  for (const u of unmapped) console.log(`  ! ${u}`);
}

if (CHECK) {
  const stale = results.some((r) => r.tasksChanged);
  console.log(stale ? "\n--check: tasks are stale (nothing written)." : "\n--check: tasks are current.");
  process.exit(stale ? 1 : 0);
}

const wrote = results.filter((r) => r.wrote);
if (wrote.length) {
  console.log(`\nUpdated ${wrote.map((r) => r.slug + "/index.html").join(", ")}.`);
}
